#Default Configuration 
# http://jekyllrb.com/docs/variables/

title: 'Test project'

time:
# The current time (when you run)

pages:  []
# A list of all Pages.

posts:  []
# A reverse chronological list of all Posts.

related_posts:  []
# If the page being processed is a Post, this contains a list of up to ten related Posts. By default, these are low quality but fast to compute. For high quality but slow to compute results, run the jekyll command with the --lsi (latent semantic indexing) option.

static_files:   []
# A list of all static files (i.e. files not processed by Jekyll's converters or the Liquid renderer).
# Each file has three properties: path, modified_time and extname.

html_pages:   []
# A list of all HTML Pages.

collections:  []
# A list of all the collections.

#data: []
# A list containing the data loaded from the YAML files located in the _data directory.

#documents:  []
# A list of all the documents in every collection.

categories: []
# categories.CATEGORY[]
# The list of all Posts in category CATEGORY.

tags: []
#tags.TAG
# The list of all Posts with tag TAG.



# http://jekyllrb.com/docs/configuration/

#	document_root
root:	'./'

#Site Source
source:      _posts

#Site Destination
destination: /var/www/html

temp:     _cache
plugins:  _plugins
layouts:  _layouts

#Disable custom plugins, and ignore symbolic links.
safe: false

# Force inclusion of files in the conversion
#files only, posts
include:  ['*.md','*.markdown','*.MD','*.twig','*.css','*.js','*.html']
# Exclude directories from the conversion
#dirs only
exclude:  ['.git','.svn']
# Exclude files
#files
notname:  []
# остальные файлы копируются всегда и записываются в массив static_files

# yaml-header in the manner
## of jekyll: --- between triple dash --- (security & default)
## of phrozn:  before triple dash ---
frontmatter: jekyll

timezone:    'Europe/Moscow'
date_format: 'Y/m/d'

encoding: 'UTF-8'

# Set defaults for YAML Front Matter variables.
# Let’s say that you want to add a default layout to all pages and posts in your site. You would add this to your _config.yml file:
# do not change please
defaults:
  scope:
    path: "projects"
    type: "pages"
  values:
    author: ''
    layout: 'post'
    id: null
    date: null
    title: ''
    content: ''
    permalink: null
    path: null
    previous: null
    next: null
    published: true
    categories: []
    tags: []




#Configuration

#Specify config files instead of using config.yml
#automatically. Settings in later files override settings in earlier files.
#config: [FILE1[,FILE2,...]]

#Process and render draft posts.
drafts: true
show_drafts: false

#Publish posts with a future date.
future: true

#Produce an index for related posts.
#lsi: true

#Limit the number of posts to parse and publish.
limit_posts: 0


#Serve Command Options

#run local server
# запускать внутренний сервер php. false = используется внешний
watch:  false

host: '127.0.0.1'
port: 4040
baseurl:  '/'
url:  '//localhost:4040'
#Detach the server from the terminal
detach: true

#	baseurl+
download_dir:	'downloads/'
code_dir:		'downloads/code/'
category_dir:	'categories/'
tag_dir:	    'tags/'

relative_permalinks: false

permalink:     'Y/m/d/title'
paginate_path: 'page:num'
transliteration:  true
categiries_path:  false # convert/and/add/relative/path/to/categories

cache:
# doctrine's adapters

  memcached:   # <-- uniq id
    adapter:
      name: Memcached   # <-- adapter's name
      persistent: false
      servers: [      ['localhost',11211,50]    ]
    priority:
      save:   100   # last
      delete: 10
      fetch:  10    # first
      precheck: true  # auto contains()
  filesystem:
    adapter:
      name: Filesystem
      dir:  ''
    priority:
      fetch:  100
      save:   10
      delete: 10





# не помню, зачем это

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true


# пс: судя по дальнейшей документации [http://jekyllrb.com/docs/posts/](http://jekyllrb.com/docs/posts/),
# все переменные этого раздела (которые дальше сливаются с _config.yml) передаются массивом site: `{{ site.url }}`.
